# Generated by Django 2.1.7 on 2019-03-03 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_id', models.CharField(max_length=200, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('start', models.CharField(max_length=200)),
                ('weight', models.FloatField()),
                ('height', models.FloatField()),
                ('time_stamp', models.DateTimeField()),
                ('location', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('email_id', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.CharField(max_length=10, unique=True)),
                ('occupation', models.CharField(max_length=200)),
            ],
        ),
    ]
